### ISSUE TITLE
pairing with `job-index` seems to be off if jobs needed

### ISSUE THREAD

**Issue by Borda** [ReeganExE/github-action-job-id#1]
This is a really great and useful tool. :rabbit: 
I was using it with some simple assumptions to pair actual jobs based on `${{ strategy.job-index }}` but when I have a few single jobs running before the main job with the matrix, the indexes seem to have some offset. Would it be possible to limit the scope only to the actual job with a matrix strategy? :otter: 
An alternative could be paring jobs based on name, not a job's index... :chipmunk: 
Just for the record, this is our use-case when I want to dum each job URL for later use: https://github.com/Lightning-AI/ecosystem-ci/pull/85

**Comment by ReeganExE** [comment]
Hi Borda, thank you for your interest.

For your case, I think you could write a simple script in your custom action, get the job list (see below) and filter everything you need.

This `step` snippet should work in public repos:

```yaml

- name: List jobs
  run: curl 'https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs?limit=22' | jq .

```

For private repo, add `-H 'authorization: Bearer ${{ github.token }}'` to the command, and give more permission to the CI as the following:

```yml
runs-on: ubuntu-latest
permissions:
  contents: read
  actions: read
```
-----
> An alternative could be paring jobs based on name, not a job's index... 🐿️

If I understand it correct, the action already has an option to expose job name as well.
```yml
      - uses: ReeganExE/github-action-job-id@v1.0
        with:
          expose-name: true
```

For example, with
```yml
generator:
  runs-on: ubuntu-latest
  steps:
  - name: ...

pytester:
  needs: generator
  runs-on: ubuntu-latest
  strategy:
    matrix:
      x: [mac, linux]
      y: [14]
```
would output:
```
GH_JOB_0_ID: ...
GH_JOB_0_RUN_URL: ...
GH_JOB_0_URL: ...
GH_JOB_0_HTML_URL: ...
GH_JOB_generator_ID: ...
GH_JOB_generator_RUN_URL: ...
GH_JOB_generator_URL: ...
GH_JOB_generator_HTML_URL: ...


GH_JOB_1_ID: ...
GH_JOB_1_RUN_URL: ...
GH_JOB_1_URL: ...
GH_JOB_1_HTML_URL: ...
GH_JOB_pytester_mac_14_ID: ...
GH_JOB_pytester_mac_14_RUN_URL: ...
GH_JOB_pytester_mac_14_URL: ...
GH_JOB_pytester_mac_14_HTML_URL: ...

GH_JOB_2_ID: ...
GH_JOB_2_RUN_URL: ...
GH_JOB_2_URL: ...
GH_JOB_2_HTML_URL: ...
GH_JOB_pytester_linux_14_ID: ...
GH_JOB_pytester_linux_14_RUN_URL: ...
GH_JOB_pytester_linux_14_URL: ...
GH_JOB_pytester_linux_14_HTML_URL: ...

```
